<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VivaCSharp</AssemblyName>
    <RootNamespace>VivaCSharp</RootNamespace>
    <EnableDefaultApplicationDefinition>true</EnableDefaultApplicationDefinition>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <EnableDefaultPageItems>true</EnableDefaultPageItems>
  </PropertyGroup>
</Project>